### ISSUE TITLE
When searching only by skills, don't mention job name

### ISSUE THREAD

**Issue by ravi-prakash-v** [beckn/DSEP-Specification#129]
In the following example,

https://github.com/beckn/DSEP-Specification/blob/master/artefacts/beckn%20specifications/jobs-internships/search/search%20request%20-%20based%20on%20skills.json

the search intent contains the name of the job. It should be possible to search only on the basis of required skills. 

Suggestions
- Remove `item.descriptor`
- Remove `item.tags[].descriptor.name`
- Update value of `item.tags[].descriptor.code` from `"skills"` to `"req-skills"`

**Comment by emmayank** [comment]
Hi @ravi-prakash-v ,

I’m pleased to inform you that the issue you reported has been successfully resolved and incorporated into the latest changes. The corresponding pull request has been merged with the `draft` branch.

**Details:**
- **PR Title:**` Issue Resolved #127, #128, #129, #130`
- **PR Link:** https://github.com/beckn/DSEP-Specification/pull/152

If you have any further questions or concerns, feel free to reach out. We appreciate your contribution and diligence in bringing this to our attention!

Best regards,
emmayank
