### ISSUE TITLE
on_search example response is not beckn protocol compliant

### ISSUE THREAD

**Issue by ravi-prakash-v** [beckn/DSEP-Specification#130]
In the following example,

https://github.com/beckn/DSEP-Specification/blob/master/artefacts/beckn%20specifications/jobs-internships/search/search%20request%20-%20only%20provider%20location.json

The `on_search` callback has the following template

```
{
    "context": {
        ...
    },
    "responses": [
        {
            "context": {
                ...
            }
        }
    ]
}
```
which is non compliant to beckn protocol message packet structure.

The correct response should be

```
{
    "context": {
        ...
    },
    "message": {
        "catalog": {
            ...
        }
    }
}
``

Please refer to the schema in https://github.com/beckn/protocol-specifications/blob/master/api/transaction/components/io/OnSearch.yaml

**Comment by emmayank** [comment]
Hi @ravi-prakash-v ,

I’m pleased to inform you that the issue you reported has been successfully resolved and incorporated into the latest changes. The corresponding pull request has been merged with the `draft` branch.

**Details:**
- **PR Title:**` Issue Resolved #127, #128, #129, #130`
- **PR Link:** https://github.com/beckn/DSEP-Specification/pull/152

If you have any further questions or concerns, feel free to reach out. We appreciate your contribution and diligence in bringing this to our attention!

Best regards,
emmayank
