### ISSUE TITLE
DSEP JSON creation: Update

### ISSUE THREAD

**Issue by meenakshi2468** [beckn/DSEP-Specification#134]
### What Needs to be built

- A JSON file to update, based on beckn specifications

**Complexity**
Medium

**Skills Required**

- JSON Schema
- Knowledge about beckn specification and format 
- DESP API specification: https://github.com/beckn/DSEP-Specification/blob/master/api/dsep.yaml

### Expected Outcome

- JSON files for both API calls (track and on_track) to be built on beckn specifications
- JSON files to be created for all four [DESP use cases](https://github.com/beckn/DSEP-Specification/tree/master/artefacts/beckn%20specifications): 1. Courses and Trainings, 2. Jobs and Internships, 3. Scholarships and Grants, 4. Tutoring and Mentorship.
- You can use the mobility [Update API](https://github.com/beckn/mobility/blob/3349a823c50db6d7242a8c951f8657918ec3dc3a/api/mobility.yaml#L902) and [on_update API](https://github.com/beckn/mobility/blob/3349a823c50db6d7242a8c951f8657918ec3dc3a/api/mobility.yaml#L3093) as a reference

### Acceptance Criteria
A properly formatted JSON file which will cater to both API scenarios (update and on_update) for all four use cases.

**Comment by emmayank** [comment]
Hi @meenakshi2468 ,

I’m pleased to inform you that the issue you reported has been successfully resolved and incorporated into the latest changes. The corresponding pull request has been merged with the `draft` branch.

**Details:**
- **PR Title:** Documentation Update & Folder Restructured
- **PR Link:** https://github.com/beckn/DSEP-Specification/pull/151

If you have any further questions or concerns, feel free to reach out. We appreciate your contribution and diligence in bringing this to our attention!

Best regards,
emmayank
